### ISSUE TITLE
Test broken.

### ISSUE THREAD

**Issue by lowks** [jjh42/githubex#2]
Tests seems to be broken when ran against 1.0.4, Traced the error down to this:

```
Compiled lib/github.ex
Generated githubex app
Interactive Elixir (1.0.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Github.user("lowks")
** (Protocol.UndefinedError) protocol String.Chars not implemented for %HTTPotion.Response{body: "Request forbidden by administrative rules. Please make sure your request has a User-Agent header (http://developer.github.com/v3/#user-agent-required). Check https://developer.github.com for other possible causes.\n", headers: ["Cache-Control": "no-cache", Connection: "close", "Content-Type": "text/html"], status_code: 403}
      (elixir) lib/string/chars.ex:3: String.Chars.impl_for!/1
      (elixir) lib/string/chars.ex:17: String.Chars.to_string/1
      (elixir) lib/io.ex:425: IO.puts/2
    (githubex) lib/github.ex:37: Github.user/2
iex(1)>
```

Is this because github changed their API ?

**Comment by jjh42** [comment]
@lowks this is not maintained (and its only really a shell). I'm not sure why exactly it is getting that error though, because it should be sending a user-agent.

Probably elixir has moved on since I wrote this, so if you want to write a github api you might be better starting from scratch.
